### ISSUE TITLE
I can not find  LINKIT 7697

### ISSUE THREAD

**Issue by kooliha** [SmallpTsai/hexapod-v2-7697#17]
You have created the perfectly designed project. I love it!

Only the problem is LINKIT 7697. They stop selling it. I cannot find it. I spent last week searching.... no luck.

Please help me :)

**Comment by ZabaLurch** [comment]
from Germany ->
Conrad -> https://www.conrad.de/de/p/seeed-studio-entwickler-platine-linkit-7697-1886943.html?gclid=EAIaIQobChMIu_Dz65Dd8gIVW0aRBR0nQARWEAAYASAAEgITzvD_BwE&ef_id=EAIaIQobChMIu_Dz65Dd8gIVW0aRBR0nQARWEAAYASAAEgITzvD_BwE%3AG%3As&hk=SEM&WT.srch=1&refresh=true

3 pieces available

**Comment by kooliha** [comment]
Thank you! 
Also found it finally here
https://www.electromaker.io/shop/product/linkit-7697
