### ISSUE TITLE
Linkit SDK is not online anymore...

### ISSUE THREAD

**Issue by Tomtom5893** [SmallpTsai/hexapod-v2-7697#20]
I need the Linkit SDK to upload a program to my linkit 7697.

It looks like mediathek has removed the sd from there page.

Does anyone have a working link for me?

Maybe we can include them in the software folder...

**Comment by mikeq3** [comment]
In the Arduino IDE preferences tab put this URL in the "Additional Boards Manager URLs" field:
http://download.labs.mediatek.com/package_mtk_linkit_7697_index.json

That should get you going.

**Comment by Tomtom5893** [comment]
Thank you so much that works
