### ISSUE TITLE
> There is 1 difference between left and right PCB. The SJ1 of right PCB is left open, but `SJ1` of left PCB should be **closed**. (This is i2c address setting of PCB9865)

### ISSUE THREAD

**Issue by dirk-asam** [SmallpTsai/hexapod-v2-7697#8]
Could you explain me what a SJ1 is? Is it an electronic part? 

Thank you

**Comment by jmfinn9** [comment]
I think it's a solder or surface jumper on the board evidently that's how the main board tells these two apart via i2c

**Comment by dirk-asam** [comment]
Helped me- Thanx
